main:
  - name: Giới Thiệu
    url: "#about"
    weight: 1
  - name: Sản Phẩm
    url: "product"
    weight: 2
  - name: Chứng Nhận
    url: "#resume"
    weight: 3
  - name: Khách Hàng
    url: "#testimonial"
    weight: 4
  - name: Bài Viết
    url: "blog"
    weight: 5
sitemap:
  - name: Giới Thiệu
    url: "#about"
    weight: 1
  - name: Sản Phẩm
    url: "product"
    weight: 2
  - name: Liên Hệ
    url: "contact"
    weight: 3
  - name: Bài Viết
    url: "blog"
    weight: 5
