main:
  - name: Chứng Nhận
    url: "#resume"
    weight: 3
  - name: Giới Thiệu
    url: "#about"
    weight: 4
  - name: Sản Phẩm
    url: "#product"
    weight: 5
  - name: Testimonials
    url: "#testimonial"
    weight: 6
  - name: Bài Viết
    url: "blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Products
    url: "product"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
