# In the Name of God, the Originator the Creative

titleSeparator: "-"
titleAddition: Công ty CP Nutriqueen
description: >-
  Healthy Food, Healthy Life, The premium quality and tasty dried fruits and nuts from
  the best farms of Iran to bring you a healthier and tastier life!
# Open Graph and Twitter Cards
images:
  - favicon.ico
ogLocale: vi_VN
# Used in Open Graph
titleHome: Nutriqueen Nhà Máy Sức Khỏe
twitterSite: "@nutriqueen"
twitterCreator: "@nutriqueen_official"
# It may be Person
schemaType: Organization
schemaName: Hyas
schemaAuthor: Henk Verlinde
schemaAuthorTwitter: "https://twitter.com/nutriqueen_official"
schemaAuthorLinkedIn: "https://www.linkedin.com/in/nutriqueen_official/"
schemaAuthorGitHub: 
schemaLocale: vi-VN
schemaLogo: logo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: hyas.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: "https://twitter.com/nutriqueen"
schemaLinkedIn: ""
schemaGitHub: "https://github.com/h-enk/hyas"
themeColor: "#3ac58d"
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - "480"
  - "720"
  - "1080"
  - "1280"
  - "1600"
  - "2048"
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: false
alertDismissable: true
alertText: >-
  Deliver web projects 10x faster. <a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get
  the free enterprise paper →</a>
blogPageURL: blog
contactLink: contact
copyright: All right reserved copyright © NutriQueen 2022
footerLogo: images/site-navigation/logo.png
footerContact:
  topTitle: Liên Hệ
  title: Mua Hàng / Đại Lý
  button: Liên Hệ Ngay
fabformURL: "https://fabform.io/f/JpTXRUa"
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/site-navigation/logo.png
address:
  address: "BT15 Trung văn - Nam Từ Liêm - Hà Nôi."
  email: info@nutriqueen.com
  openingHours: Open from 10am to 6pm (close at 5pm Sundays)
  phone: (+84) 858.895.668
map:
  APIkey: YOUR GOOGLE MAP API
  latitude: "23.7783741"
  longitude: "90.3746808"
  pinImage: images/pin.png
social:
  - icon: fa-facebook-official
    url: "https://www.facebook.com/vinhthinhvuong.vn/"
    weight: 1
  - icon: fa-shopping-bag
    url: "https://www.lazada.vn/shop/nutriqueen-offical-store/"
    weight: 2
